### PR TITLE
For consistency with MediaWiki, rename all references to type 'photo' to 'image'

### PR DESCRIPTION
**Pull request by kflorence**
**DO NOT MERGE YET** breaks production parsoid

### CODE REVIEW

**Comment by wladekb** [comment]
@inez ping

**Comment by wladekb** [comment]
@inez this PR is kind of old (waiting more than a year), please decide to either merge it or close it

**Comment by kflorence** [comment]
Blast from the past. Hey @wladekb :)

**Comment by wladekb** [comment]
Hey @kflorence :)

**Comment by inez** [comment]
@wladekb Thanks for reminding. I'm not able to handle it yet - is still breaks production & I'm very busy with VE upstream sync. I will get back to it later (but yeah - the change overall is good, and we want it).

**Comment by wladekb** [comment]
@inez will the time come for this one soon?

**Pull request closed without merging**
