### PR TITLE
jshashes version

### PR DESCRIPTION
**Pull request by ljagiello**
<code>
npm ERR! Error: No compatible version found: jshashes@'>=0.0.0- <1.0.0-'
npm ERR! Valid install targets:
npm ERR! ["1.0.2","1.0.3"]
npm ERR!     at installTargetsError (/usr/lib/nodejs/npm/lib/cache.js:674:10)
npm ERR!     at next (/usr/lib/nodejs/npm/lib/cache.js:653:17)
npm ERR!     at /usr/lib/nodejs/npm/lib/cache.js:633:5
npm ERR!     at saved (/usr/lib/nodejs/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at /usr/lib/nodejs/npm/node_modules/graceful-fs/graceful-fs.js:218:7
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
</code>

jshashes is only now available in version "1.0.2" and "1.0.3".

### CODE REVIEW

**Comment by owend** [comment]
Is this something we might pull from upstream?  Or merge back?

**Comment by ljagiello** [comment]
Good question, upstream stop using jshashes and migrate into crypto. I'm not sure what way we should go.

https://github.com/wikimedia/mediawiki-extensions-Parsoid/commit/d7bb4fb4b86d9f03e49e4b2aa42de60084bd864b#js/package.json

Reason why they change jshashes into crypto isn't valid atm, but still maybe easier will be just merge with upstream. Definitely we should do something with that because it's not working atm.

**Comment by cscott** [comment]
jshashes upstream was very broken (returned the same hash for every value).  I fixed it, which resulted in the new version of jshashes (and the reason the old versions were removed from npm).  I also removed parsoid's dependency on jshashes at the same time, because the fact that the bug existed in the first place said terrible things about the upstream code quality.

**Comment by kflorence** [comment]
@inez Is this still valid?

**Comment by inez** [comment]
As far as I know - not at all - closing now.

**Pull request closed without merging**
